# Generated by Django 3.0.8 on 2020-08-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcadTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_year', models.IntegerField(verbose_name='Target Year')),
            ],
        ),
        migrations.CreateModel(
            name='AcadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acad_type', models.CharField(max_length=2, verbose_name='Academic Session')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=1, verbose_name='Class Code')),
                ('grade', models.IntegerField(verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('center', models.CharField(max_length=20, verbose_name='Center Location')),
                ('center_id', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Center Code')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=25, verbose_name='Student Name')),
                ('phn_pri', models.CharField(max_length=10, verbose_name='Primary Phone')),
                ('s_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phn_sec', models.CharField(blank=True, max_length=10, null=True, verbose_name='Other Phone')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.AcadType')),
                ('target_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.AcadTarget')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.StudyCenter'),
        ),
        migrations.AddField(
            model_name='batch',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Grade'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Section'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sessionCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.SessionCode'),
        ),
    ]
