# Generated by Django 3.0.8 on 2020-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=25, verbose_name='Student Name')),
                ('phn_pri', models.IntegerField(verbose_name='Primary Phone')),
                ('batch_code', models.CharField(max_length=5, verbose_name='Batch Code')),
                ('s_email', models.EmailField(default='not availaible', max_length=254, verbose_name='Email')),
                ('phn_sec', models.IntegerField(default=0, verbose_name='Secondary Phone')),
            ],
        ),
    ]
