# Generated by Django 3.0.8 on 2020-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phn_pri',
            field=models.CharField(max_length=10, verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_sec',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Other Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
