# Generated by Django 3.0.8 on 2020-08-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='fee',
            field=models.IntegerField(default=300, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='acadtype',
            name='acad_type',
            field=models.CharField(max_length=2, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='FeesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_paid', models.IntegerField(default=300, verbose_name='Value')),
                ('isOnline', models.BooleanField(verbose_name='Mode Online?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Student')),
            ],
        ),
    ]
