# Generated by Django 3.0.8 on 2020-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='acadType',
            field=models.CharField(choices=[('MP', 'Madhyamik'), ('HS', 'Higher Secondary')], max_length=2),
        ),
        migrations.DeleteModel(
            name='AcadType',
        ),
    ]
