# Generated by Django 3.0.8 on 2020-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20200805_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='acadTarget',
            field=models.CharField(choices=[('21', '2021'), ('22', '2022'), ('23', '2023')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='feesRecords',
            field=models.ManyToManyField(blank=True, to='student_management.FeesRecord'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('H', '8'), ('M', '9'), ('R', '10'), ('B', '11'), ('S', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studyCenter',
            field=models.CharField(choices=[('O', 'Bari Shalbagan')], max_length=2),
        ),
        migrations.DeleteModel(
            name='AcadTarget',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='StudyCenter',
        ),
    ]
