# Generated by Django 3.0.8 on 2020-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20200805_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feesRecords',
            field=models.ManyToManyField(to='student_management.FeesRecord'),
        ),
    ]
