# Generated by Django 3.0.8 on 2020-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20200805_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('-', 'Not Assigned')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studyCenter',
            field=models.CharField(choices=[('O', 'Bari Shalbagan'), ('M', 'Madhyamgram'), ('B', 'Bagbazar'), ('R', 'Station'), ('C', 'Champadali'), ('K', 'Kailashnagar'), ('S', 'Sodepur'), ('-', 'Not Assigned')], max_length=2),
        ),
    ]
